
#ifndef SEARCHSTRATEGY_EXPORT_H
#define SEARCHSTRATEGY_EXPORT_H

#ifdef SEARCHSTRATEGY_STATIC_DEFINE
#  define SEARCHSTRATEGY_EXPORT
#  define SEARCHSTRATEGY_NO_EXPORT
#else
#  ifndef SEARCHSTRATEGY_EXPORT
#    ifdef SearchStrategy_EXPORTS
        /* We are building this library */
#      define SEARCHSTRATEGY_EXPORT 
#    else
        /* We are using this library */
#      define SEARCHSTRATEGY_EXPORT 
#    endif
#  endif

#  ifndef SEARCHSTRATEGY_NO_EXPORT
#    define SEARCHSTRATEGY_NO_EXPORT 
#  endif
#endif

#ifndef SEARCHSTRATEGY_DEPRECATED
#  define SEARCHSTRATEGY_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SEARCHSTRATEGY_DEPRECATED_EXPORT
#  define SEARCHSTRATEGY_DEPRECATED_EXPORT SEARCHSTRATEGY_EXPORT SEARCHSTRATEGY_DEPRECATED
#endif

#ifndef SEARCHSTRATEGY_DEPRECATED_NO_EXPORT
#  define SEARCHSTRATEGY_DEPRECATED_NO_EXPORT SEARCHSTRATEGY_NO_EXPORT SEARCHSTRATEGY_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SEARCHSTRATEGY_NO_DEPRECATED
#    define SEARCHSTRATEGY_NO_DEPRECATED
#  endif
#endif

#endif /* SEARCHSTRATEGY_EXPORT_H */
